name: Build Node.js App with docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: permission adjust 
        run: sudo chmod 600 TeraKey.pem

      - name: copy files to server 
        run: scp -o StrictHostKeyChecking=no -i TeraKey.pem -r * ec2-user@3.237.94.126:/home/ec2-user/projectD

      - name: Trigger depl script
        run: ssh -o StrictHostKeyChecking=no -i TeraKey.pem  ec2-user@3.237.94.126   nohup /home/ec2-user/projectD/node.sh &